name: Terraform CI/CD Pipeline for deployment
run-name: ${{ github.actor }} has triggered the pipeline #authenticated user
on:
  push:
    branches:
      - 'feature'
env: #environment variables
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  Infra-automation:
    - name: CI/CD Deployment
    runs-on: ubuntu-latest# Remove the .terraform directory physically (optional)
    Remove-Item -Recurse -Force Tf-VPC/.terraform/
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./Tf-VPC
    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ./TC-VPC
    - name: Terraform Plan
      run: terraform plan
      working-directory: ./Tf-VPC
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve
      working-directory: ./Tf-VPC